# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Divergent
subtitle: 分歧者，拥有强烈好奇心的异类
description: 今天，终会成为过去，唯一能留住的就是未来
author: Dannii
language: zh-CN
timezone: Asia/Shanghai

# leancloud
leancloud_counter_security:
  enable_sync: true
  app_id: CN3rYnRBptO8quKX4O42PyJh-gzGzoHsz
  app_key: lvCfzqdKlX5mHzPNamk4Swqy
  server_url: https://cn3rynrb.lc-cn-n1-shared.com # Required for apps from CN region, e.g. https://leancloud.cn
  username:  # Will be asked while deploying if is left blank
  password:  # Recommmended to be left blank. Will be asked while 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://dannii.cc
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: 
  enable: true # Open external links in new tab
  field: site
  exclude: []
filename_case: 0
render_drafts: false
marked:
  prependRoot: true
  postAsset: true
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  pagination_dir: page
  
# Category & Tag
default_category: uncategorized
category_map:
  「这就是生活」: life
  「书影世界」: bookandmovie
  「你好，手工艺」: craftsmanship
  「进化之路」: self-growth
  「跟黑洞一样大的脑坑」: novel
  「get新技能」: newskill
  「随手记」: notes
tag_map:
  “更无用”的写作课-作业: wuyong-writing-work
  “更无用”的写作课-笔记: wuyong-writing-note
  读书笔记: reading-notes
  理财: finance

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
# hexo-theme-next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repository: https://github.com/hormoyo/hormoyo.github.io.git
  branch: master

#统计字数
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  wpm: 300
  suffix: "mins."

#rss订阅
feed:
  type: rss2
  path: rss2.xml
  limit: 10
  hub:
  content: 'true'

#本地搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
  content: true

# douban 豆瓣个人主页的小插件
# 参看：https://github.com/mythsman/hexo-douban
# 升级可以用：修改package.json内hexo-douban的版本号至最新
# 重新安装最新版本npm install hexo-douban --save
# 或者使用npm install hexo-douban --update --save直接更新
douban:
  id: 1563307
  builtin: true
  item_per_page: 10
  meta_max_line: 4
  customize_layout: page
  book:
    path: books/index.html
    title: 书破万卷
    quote: 读书当破万卷，方得世间如意
    option:
  movie:
    path: movies/index.html
    title: 观世间相
    quote: 电影始于格里菲斯，止于基亚罗斯塔米
    option:
  #game:
   # title: 'This is my game title'
   # quote: 'This is my game quote'
  timeout: 10000 
# user用"个人主页" ，这时候地址栏的URL大概是这样："https://www.douban.com/people/xxxxxx/"，其中的"xxxxxx"就是你的个人ID了
# id获取的一个已知的办法是：访问“我的豆瓣“时，点击用户头像另存为时，会显示默认文件名如ul2374908-5。中间数字2374908即为豆瓣数字ID。
# builtin为true则hexo d和hexos的时候内嵌了生成页面功能，否则使用hexo douban指令
# option: 该页面额外的 Front-matter 配置，参考Hexo 文档。无特别需要，留空即可。